version: '2'
distribution_spec:
  description: Use SambaNova for running LLM inference and safety
  providers:
    inference:
    - remote::sambanova
    - inline::sentence-transformers
    vector_io:
    - inline::faiss
    - remote::chromadb
    - remote::pgvector
    safety:
    - remote::sambanova
    agents:
    - inline::meta-reference
    telemetry:
    - inline::meta-reference
    tool_runtime:
    - remote::brave-search
    - remote::tavily-search
    - inline::rag-runtime
    - remote::model-context-protocol
    - remote::wolfram-alpha
image_type: conda
additional_pip_packages:
- aiosqlite
- sqlalchemy[asyncio]
