name: Setup runner
description: Prepare a runner for the tests (install uv, python, project dependencies, etc.)
inputs:
  python-version:
    description: The Python version to use
    required: false
    default: "3.12"
  client-version:
    description: The llama-stack-client-python version to test against (latest or published)
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1
      with:
        python-version: ${{ inputs.python-version }}
        activate-environment: true
        version: 0.7.6

    - name: Install dependencies
      shell: bash
      run: |
        uv sync --all-groups
        uv pip install ollama faiss-cpu

        # Install llama-stack-client-python based on the client-version input
        if [ "${{ inputs.client-version }}" = "latest" ]; then
          echo "Installing latest llama-stack-client-python from main branch"
          uv pip install git+https://github.com/meta-llama/llama-stack-client-python.git@main
        elif [ "${{ inputs.client-version }}" = "published" ]; then
          echo "Installing published llama-stack-client-python from PyPI"
          uv pip install llama-stack-client
        else
          echo "Invalid client-version: ${{ inputs.client-version }}"
          exit 1
        fi

        uv pip install -e .
