version: '2'
name: experimental-post-training
distribution_spec:
  description: Experimental template for post training
  container_image: null
  providers:
    inference:
    - inline::meta-reference
    - remote::ollama
    eval:
    - inline::meta-reference
    scoring:
    - inline::basic
    - inline::braintrust
    post_training:
    - inline::torchtune
    datasetio:
    - inline::localfs
    telemetry:
    - inline::meta-reference
    agents:
    - inline::meta-reference
    safety:
    - inline::llama-guard
    vector_io:
    - inline::faiss
    tool_runtime:
    - remote::brave-search
image_type: conda
