[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "llama-stack-provider-tool-runtime-model-context-protocol"
version = "0.1.0"
description = "Model Context Protocol (MCP) tool for standardized tool calling and context management"
authors = [{ name = "Meta Llama", email = "llama-oss@meta.com" }]
requires-python = ">=3.12"
license = { "text" = "MIT" }
dependencies = [
    "mcp>=1.8.1",
]



[tool.setuptools.packages.find]
where = ["."]
include = ["llama_stack*"]
