version: 2
distribution_spec:
  description: Dell's distribution of Llama Stack. TGI inference via Dell's custom
    container
  providers:
    inference:
    - provider_type: remote::tgi
    - provider_type: inline::sentence-transformers
    vector_io:
    - provider_type: inline::faiss
    - provider_type: remote::chromadb
    - provider_type: remote::pgvector
    safety:
    - provider_type: inline::llama-guard
    agents:
    - provider_type: inline::meta-reference
    telemetry:
    - provider_type: inline::meta-reference
    eval:
    - provider_type: inline::meta-reference
    datasetio:
    - provider_type: remote::huggingface
    - provider_type: inline::localfs
    scoring:
    - provider_type: inline::basic
    - provider_type: inline::llm-as-judge
    - provider_type: inline::braintrust
    tool_runtime:
    - provider_type: remote::brave-search
    - provider_type: remote::tavily-search
    - provider_type: inline::rag-runtime
image_type: conda
image_name: dell
additional_pip_packages:
- aiosqlite
- sqlalchemy[asyncio]
