[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "llama-stack-provider-vector-io-milvus-remote"
version = "0.1.0"
description = "Milvus remote vector database provider for Llama Stack"
authors = [{ name = "Meta Llama", email = "llama-oss@meta.com" }]
requires-python = ">=3.12"
license = { "text" = "MIT" }
dependencies = [
    "pymilvus>=2.4.10",
]



[tool.setuptools.packages.find]
where = ["."]
include = ["llama_stack*"]
