# Set up default storage class on AWS EKS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-topology-aware
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
provisioner: ebs.csi.eks.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
