[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "llama-stack-provider-safety-bedrock"
version = "0.1.0"
description = "AWS Bedrock safety provider for content moderation using AWS's safety services"
authors = [{ name = "Meta Llama", email = "llama-oss@meta.com" }]
requires-python = ">=3.12"
license = { "text" = "MIT" }
dependencies = [
    "boto3",
]



[tool.setuptools.packages.find]
where = ["."]
include = ["llama_stack*"]
