[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "llama-stack-provider-safety-sambanova"
version = "0.1.0"
description = "SambaNova's safety provider for content moderation and safety filtering"
authors = [{ name = "Meta Llama", email = "llama-oss@meta.com" }]
requires-python = ">=3.12"
license = { "text" = "MIT" }
dependencies = [
    "litellm",
    "requests",
]



[tool.setuptools.packages.find]
where = ["."]
include = ["llama_stack*"]
