name: Integration-test

on:
  workflow_dispatch:
  push:

run-name:
  "CI test"

env:
  TESTS_PATH: "${{ github.workspace }}/llama_stack/providers/tests"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'


  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs:
      build
    steps:
      - name: "Checkout 'meta-llama/llama-stack' repository"
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install -U \
            torch torchvision \
            pytest pytest_asyncio \
            fairscale lm-format-enforcer \
            zmq chardet pypdf \
            pandas sentence_transformers together \
            aiosqlite groq ollama fireworks \
            pytest-html pytest-asyncio

      - name: Run integration test
        working-directory: "${{ github.workspace }}"
        run: |
          export FIREWORKS_API_KEY=${{ secrets.FIREWORKS_API_KEY }}
          export TOGETHER_API_KEY=${{ secrets.TOGETHER_API_KEY }}
          echo "Current directory: $(pwd)"
          echo "Repository root: ${{ github.workspace }}"
          echo "Branch: ${{ github.ref }}"
          echo "List of tests"
          pytest ${{ github.workspace }}/llama_stack/providers/tests/ --html=report.html --config=ci_test_config.yaml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: report.html
          path: report.html
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
