name: Check semantic PR titles

run-name: Ensure that PR titles follow the conventional commit spec

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title's semantic conformance
        uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
